"""
FastPDF Basic Usage Examples
============================

Run: python examples/basic_usage.py
"""

from fastpdf import render_pdf, render_pdf_to_file, RenderOptions, PdfEngine


def example_simple():
    """Simplest possible PDF generation."""
    pdf_bytes = render_pdf("<h1>Hello, FastPDF!</h1>")
    with open("output/simple.pdf", "wb") as f:
        f.write(pdf_bytes)
    print(f"✓ Simple PDF: {len(pdf_bytes)} bytes")


def example_styled():
    """PDF with inline CSS styling."""
    html = """
    <html>
    <head>
        <style>
            body { font-family: Helvetica, sans-serif; color: #333; }
            h1 { color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 10px; }
            .content { margin: 20px 0; line-height: 1.6; }
            .highlight { background-color: #fef3c7; padding: 2px 6px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #1a56db; color: white; padding: 12px; text-align: left; }
            td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }
            tr:nth-child(even) { background-color: #f9fafb; }
        </style>
    </head>
    <body>
        <h1>Styled Document</h1>
        <div class="content">
            <p>This is a <span class="highlight">styled PDF</span> generated with FastPDF.</p>
            <p>It supports full CSS styling including colors, fonts, tables, and more.</p>
        </div>
        <table>
            <thead>
                <tr><th>Feature</th><th>Status</th><th>Performance</th></tr>
            </thead>
            <tbody>
                <tr><td>HTML Parsing</td><td>✓ Complete</td><td>&lt;1ms</td></tr>
                <tr><td>CSS Styling</td><td>✓ Complete</td><td>&lt;2ms</td></tr>
                <tr><td>Layout Engine</td><td>✓ Complete</td><td>&lt;5ms</td></tr>
                <tr><td>PDF Generation</td><td>✓ Complete</td><td>&lt;10ms</td></tr>
            </tbody>
        </table>
    </body>
    </html>
    """
    render_pdf_to_file(html, "output/styled.pdf")
    print("✓ Styled PDF generated")


def example_with_options():
    """PDF with custom rendering options."""
    html = "<h1>Letter Size Document</h1><p>This uses Letter paper with custom margins.</p>"
    
    options = RenderOptions(
        page_size="Letter",
        orientation="portrait",
        margin_top=25.0,
        margin_right=20.0,
        margin_bottom=25.0,
        margin_left=20.0,
        title="Custom Options Example",
        author="FastPDF",
    )
    
    doc = render_pdf_to_file(html, "output/custom_options.pdf", options=options)
    print(f"✓ Custom options PDF: {doc.page_count} pages, {doc.title}")


def example_with_css():
    """PDF with separate CSS."""
    html = """
    <h1>Document with External CSS</h1>
    <p class="intro">This document uses a separate CSS string.</p>
    <ul>
        <li>Clean separation of content and style</li>
        <li>Easy to maintain and test</li>
        <li>Reusable stylesheets</li>
    </ul>
    """
    
    css = """
    body { font-family: Georgia, serif; max-width: 600px; margin: 0 auto; }
    h1 { color: #7c3aed; }
    .intro { font-size: 14pt; color: #6b7280; font-style: italic; }
    li { margin: 8px 0; }
    """
    
    pdf_bytes = render_pdf(html, css=css)
    with open("output/external_css.pdf", "wb") as f:
        f.write(pdf_bytes)
    print("✓ External CSS PDF generated")


def example_engine():
    """Using PdfEngine for multiple renders with shared config."""
    engine = PdfEngine(
        default_options=RenderOptions(
            page_size="A4",
            title="Batch Document",
            tailwind=False,
        ),
    )

    for i in range(5):
        html = f"<h1>Document {i + 1}</h1><p>Page content for document {i + 1}.</p>"
        doc = engine.render(html)
        doc.save(f"output/batch_{i + 1}.pdf")

    print("✓ 5 batch documents generated via PdfEngine")


def example_tailwind():
    """PDF with Tailwind CSS utility classes."""
    html = """
    <div class="p-8 max-w-2xl mx-auto">
        <h1 class="text-3xl font-bold text-blue-600 mb-4">Tailwind Styled</h1>
        <p class="text-gray-600 text-lg mb-6">
            This document uses Tailwind CSS utility classes for styling.
        </p>
        <div class="bg-gray-100 rounded-lg p-6 mb-6">
            <h2 class="text-xl font-semibold text-gray-800 mb-2">Features</h2>
            <ul class="text-gray-700">
                <li class="mb-2">✓ Utility-first CSS without a build step</li>
                <li class="mb-2">✓ Responsive spacing and typography</li>
                <li class="mb-2">✓ Color palette support</li>
            </ul>
        </div>
        <div class="flex justify-between border-t pt-4">
            <span class="text-sm text-gray-500">Generated by FastPDF</span>
            <span class="text-sm font-medium text-blue-600">v0.1.0</span>
        </div>
    </div>
    """
    
    options = RenderOptions(tailwind=True, title="Tailwind Example")
    pdf_bytes = render_pdf(html, options=options)
    with open("output/tailwind.pdf", "wb") as f:
        f.write(pdf_bytes)
    print("✓ Tailwind CSS PDF generated")


def example_batch():
    """Parallel batch rendering."""
    items = [
        {"html": f"<h1>Invoice #{i}</h1><p>Amount: ${i * 100:.2f}</p>"}
        for i in range(1, 11)
    ]
    
    from fastpdf import batch_render
    results = batch_render(items)
    
    for i, pdf_bytes in enumerate(results, 1):
        with open(f"output/invoice_{i}.pdf", "wb") as f:
            f.write(pdf_bytes)
    
    print(f"✓ {len(results)} invoices rendered in parallel")


if __name__ == "__main__":
    import os
    os.makedirs("output", exist_ok=True)
    
    print("FastPDF Basic Usage Examples")
    print("=" * 40)
    
    example_simple()
    example_styled()
    example_with_options()
    example_with_css()
    example_engine()
    example_tailwind()
    example_batch()
    
    print("\n✓ All examples completed! Check the output/ directory.")
